setw -g mode-keys vi
setw -g history-limit 10000
bind-key P capture-pane -S -50000 \; save-buffer ~/tmux.tmp \; run-shell 'FNAME=`mktemp -p ~/ -t tmuxXXXX.tmux`;cp ~/tmux.tmp $FNAME;'
set-option -g allow-rename off
set -g default-terminal "screen-256color"
set -g status-bg colour232
set -g status-fg colour39
set -g prefix `
bind-key ` send-prefix
